name: CI Pipeline

on:
  push:
    branches: [master]  # Запускать только при пуше в ветку master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Установка зависимостей
        run: npm ci
      
      - name: Сохранение node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules/

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Восстановление node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: ./
      
      - name: Установка бинарных файлов
        run: npm ci --ignore-scripts
      
      - name: Линтинг
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Восстановление node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: ./
      
      - name: Установка бинарных файлов
        run: npm ci --ignore-scripts
      
      - name: Запуск тестов
        run: npm test
